name: Deploy Frontend to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'
  workflow_dispatch: # Allows manual trigger from GitHub Actions tab

# Set permissions for the GitHub token to allow deployment
permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Checkout repository 🛎️
        uses: actions/checkout@v4

      - name: Deploy to GitHub Pages 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: frontend # Deploys only the contents of the frontend directory
          branch: gh-pages # Deploys to the gh-pages branch
